package printer

import kotlin.random.Random

class ProverbPrinter(
  executor: CommandExecutor = DefaultCommandExecutor(),
) : BasePrinter(executor) {

  override fun print(): Result<Unit> {
    val text = randomProverb()
    return withTempFiles { pngFile, binFile ->
      runConvert("caption:$text", pngFile, size = "696x400", pointSize = "40")
      runBrotherQlCreate(pngFile, binFile)

      runLp(binFile)
    }
  }

  companion object {
    fun randomProverb(random: Random = Random): String = CHINESE_PROVERBS_PT.random(random)

    private val CHINESE_PROVERBS_PT = listOf(
      "A alegria que você espalha hoje volta para descansar no seu coração amanhã.",
      "A bondade que você oferece hoje constrói a ponte que você atravessará amanhã.",
      "A calma na tempestade é a verdadeira força do guerreiro.",
      "A cada amanhecer, a vida lhe entrega um rolo em branco: escreva com sabedoria.",
      "A confiança é um vaso de porcelana: cuide para não deixá-lo cair.",
      "A coragem não é ausência de medo, é caminhar com medo mesmo assim.",
      "A disciplina de hoje é a liberdade de amanhã.",
      "A folha que cai não discute com o vento, apenas aceita o próximo lugar.",
      "A gratidão transforma o pouco em suficiente e o suficiente em abundância.",
      "A jornada mais longa se vence com passos pequenos e constantes.",
      "A luz de uma pequena vela vence a escuridão de um grande salão.",
      "A mente que se abre para aprender nunca volta ao tamanho anterior.",
      "A paciência é o chá quente que acalma o coração apressado.",
      "A palavra dita com cuidado impede mil arrependimentos.",
      "A palavra que feriu hoje pode ecoar por muitos invernos.",
      "A raiz profunda não teme o vento mais forte.",
      "A sabedoria não grita, apenas espera ser ouvida.",
      "A sombra dos problemas é sempre maior do que o problema.",
      "A sorte visita primeiro a casa de quem se prepara.",
      "A verdadeira vitória é vencer a si mesmo todos os dias.",
      "A vida floresce onde o coração é regado com esperança.",
      "Abra espaço para o novo deixando o velho descansar em paz.",
      "Abra o coração como quem abre uma janela para a primavera.",
      "Abrace suas falhas como mestres que apontam o próximo passo.",
      "Aceite o que não pode mudar e mude com coragem o que pode.",
      "Antes de acusar a escuridão, acenda uma centelha de luz.",
      "Antes de exigir respeito, aprenda a oferecê-lo em silêncio.",
      "Antes de se irritar com a chuva, lembre-se da colheita.",
      "Aprenda com o bambu: ele se curva sem quebrar.",
      "Aprenda com o rio: ele vence a pedra sem precisar ser duro.",
      "Aquilo que você alimenta em silêncio se torna o seu destino.",
      "As melhores respostas chegam quando a mente para de gritar.",
      "As montanhas não se movem, mas o caminho em volta delas sempre existe.",
      "As palavras que você escolhe constroem a casa onde sua alma mora.",
      "As raízes do respeito dão frutos de paz por muitos anos.",
      "Atrás de cada dificuldade se esconde uma oportunidade tímida.",
      "Atrase a raiva, adiante a compreensão e verá o dia ficar mais leve.",
      "Basta uma faísca de esperança para afastar a noite da alma.",
      "Boca que vive reclamando nunca sente o sabor da gratidão.",
      "Busque a paz dentro de si, e o mundo ao redor ficará menos barulhento.",
      "Cada gesto de bondade é um tijolo no templo da sua história.",
      "Cada lágrima rega uma nova flor de entendimento.",
      "Cada manhã é um dragão adormecido esperando sua coragem acordar.",
      "Cada silêncio carrega uma resposta que as palavras não conseguem dar.",
      "Cada sorriso que você oferece ilumina dois rostos: o seu e o de quem recebe.",
      "Caminhe leve: quem leva muito peso na alma se cansa depressa.",
      "Caminhar devagar ainda é muito melhor do que ficar parado.",
      "Céu nublado não apaga o sol, apenas o esconde por instantes.",
      "Com calma, até uma montanha se torna apenas muitos pedregulhos.",
      "Compreender o erro é mais sábio do que apenas apontá-lo.",
      "Confie: nenhuma noite foi tão longa que o amanhecer não chegasse.",
      "Conhecer a si mesmo é a viagem mais longa e mais importante.",
      "Coração apressado tropeça em detalhes que o coração calmo enxerga.",
      "Coração que sabe esperar transforma atraso em proteção.",
      "Cultive bons pensamentos e você terá um jardim dentro da cabeça.",
      "De olhos mansos vê-se melhor o caminho do outro.",
      "De nada adianta o barco mais belo se o remador não tem direção.",
      "Depois da chuva, até a pedra aprende a brilhar.",
      "Desapegue do que pesa e veja como o caminho fica mais curto.",
      "Descanse a mente para enxergar o que o cansaço esconde.",
      "Deus do acaso visita pouco a casa do preguiçoso.",
      "Devagar também é caminho, desde que seja para a frente.",
      "Diante de uma porta fechada, aprenda a construir janelas.",
      "Diga menos, faça mais: o mundo confia mais nos passos que nas promessas.",
      "Do solo mais duro nascem flores que surpreendem a primavera.",
      "Dos espinhos do hoje surgem as rosas do amanhã.",
      "Enquanto a língua fala, o coração revela quem realmente somos.",
      "Enquanto você olha só para o topo, esquece que a montanha começa no chão.",
      "Entre ter razão e ter paz, escolha a paz e a razão chegará.",
      "Escutar com atenção é um abraço invisível.",
      "Esqueça as pedras que passaram e aprenda com as marcas que deixaram.",
      "Espere com paciência, mas prepare-se com dedicação.",
      "Faça do silêncio um aliado e da calma um escudo.",
      "Faça hoje algo de que seu futuro possa se orgulhar.",
      "Flores de respeito perfumam qualquer ambiente.",
      "Floresça onde a vida decidiu lhe plantar.",
      "Há caminhos que só aparecem para quem continua caminhando.",
      "Há dias em que a melhor resposta é um sorriso tranquilo.",
      "Há derrotas que livram você de guerras perigosas.",
      "Há tesouros escondidos nas coisas simples de todos os dias.",
      "Jamais subestime o poder de um gesto pequeno, feito com grande amor.",
      "Lembre-se: até o bambu começou como uma semente invisível.",
      "Lembre-se de quem segurou sua mão quando o chão faltou.",
      "Língua afiada faz mais cortes que qualquer espada.",
      "Limpe o coração como quem varre a porta de casa todas as manhãs.",
      "Mais vale um passo sincero do que um salto cheio de medo.",
      "Mantenha a mente flexível; o galho rígido é o primeiro a quebrar.",
      "Mais importante que chegar primeiro é chegar inteiro.",
      "Mesmo o maior rio já foi uma pequena nascente tímida.",
      "Mesmo o dragão mais forte precisa descansar as asas.",
      "Na pressa de vencer, muitos esquecem de aprender.",
      "Na serenidade, o coração escuta conselhos que o barulho esconde.",
      "Na sutileza de um olhar cabem segredos que mil palavras não explicam.",
      "Nada pesa tanto quanto uma culpa que podia ter virado perdão.",
      "Nada protege melhor que uma consciência tranquila.",
      "Nenhuma árvore cresce se tiver medo do vento.",
      "Nenhuma boa semente é perdida quando lançada em solo de boa vontade.",
      "Nenhum esforço sincero retorna de mãos vazias.",
      "Nenhum inverno é eterno: até ele sabe quando deve ir embora.",
      "Nenhum passo é pequeno demais quando se anda em direção ao sonho.",
      "Nenhum sorriso dado por bondade é desperdiçado.",
      "Nunca é tarde para recomeçar por dentro.",
      "Nunca falta caminho para quem não tem medo de mudar a rota.",
      "Nunca negocie sua paz por uma vitória pequena.",
      "Nunca subestime o eco de uma palavra gentil.",
      "O coração aberto atrai caminhos que o medo não consegue ver.",
      "O coração generoso nunca volta pobre de uma visita.",
      "O coração humilde aprende até com o silêncio.",
      "O coração que perdoa dorme em travesseiro macio.",
      "O destino abre portas, mas são suas escolhas que decidem por onde entrar.",
      "O erro de hoje pode ser o mestre de amanhã, se você o escutar.",
      "O gesto que você esquece pode ser o que o outro lembra para sempre.",
      "O mar não se orgulha das ondas, apenas continua sendo mar.",
      "O medo enxerga paredes; a confiança enxerga portas.",
      "O orgulhoso tropeça nas próprias palavras antes de cair nos próprios passos.",
      "O que você alimenta em segredo se torna gigante no seu caminho.",
      "O que você faz quando ninguém vê define quem você é.",
      "O que você planta em pensamentos nasce em atitudes.",
      "O que você procura no céu às vezes está escondido dentro do peito.",
      "O silêncio sábio vale mais do que mil explicações apressadas.",
      "O sorriso tranquilo desarma tempestades invisíveis.",
      "O tempo é um professor que não aceita suborno.",
      "O tempo que você usa para se preocupar poderia estar construindo soluções.",
      "O vento leva folhas secas, mas fortalece os galhos que resistem.",
      "Onde entra a luz da compreensão, sai a sombra do julgamento.",
      "Onde há respeito, até o silêncio é confortável.",
      "Onde há verdade, a mentira não consegue ficar muito tempo.",
      "Os caminhos se abrem para quem não desiste de andar.",
      "Os dias mais difíceis treinam o coração para as maiores vitórias.",
      "Os olhos que procuram beleza sempre a encontram em algum lugar.",
      "Os pequenos gestos de hoje se tornam grandes lembranças amanhã.",
      "Para quem tem coragem, até a dúvida vira ponte.",
      "Para ver o céu estrelado é preciso aceitar algumas noites escuras.",
      "Perdoar é libertar dois prisioneiros: o outro e você mesmo.",
      "Pés firmes e coração leve atravessam qualquer ponte.",
      "Pensar antes de falar é como afiar o machado antes de cortar a árvore.",
      "Perder-se de vez em quando ajuda a encontrar novos caminhos.",
      "Procure ser paz em vez de ter sempre razão.",
      "Quando a alma está em paz, qualquer lugar vira templo.",
      "Quando a esperança entra pela porta, o medo sai pela janela.",
      "Quando a intenção é boa, até o erro vira aprendizado.",
      "Quando a mente se aquieta, o coração começa a falar.",
      "Quando a raiva assume o comando, a sabedoria sai pela porta dos fundos.",
      "Quando a tempestade passa, o céu volta ainda mais azul.",
      "Quando aprender a esperar, o tempo deixará de ser inimigo.",
      "Quando o coração sorri, os olhos não conseguem esconder.",
      "Quando o orgulho grita, a verdade se afasta.",
      "Quando o vento muda, não lute contra ele: ajuste as velas.",
      "Quando você muda por dentro, o mundo ao redor muda de cor.",
      "Quem acende a luz para o outro também ilumina o próprio caminho.",
      "Quem acolhe conselhos encurta o caminho dos próprios erros.",
      "Quem aprende com o passado ganha asas para o futuro.",
      "Quem caminha com gentileza deixa pegadas de flores.",
      "Quem carrega gratidão no peito nunca viaja sozinho.",
      "Quem cuida do hoje recebe um amanhã mais leve.",
      "Quem domina a si mesmo é mais forte que quem conquista cidades.",
      "Quem escuta mais do que fala aprende duas vezes.",
      "Quem fala com respeito é bem-vindo em qualquer lugar.",
      "Quem guarda rancor guarda fogo em vasilha de papel.",
      "Quem levanta o outro também se eleva.",
      "Quem leva luz não teme caminhos escuros.",
      "Quem não erra não descobre novos caminhos.",
      "Quem não respeita o pouco não merece o muito.",
      "Quem não sabe parar também não sabe recomeçar.",
      "Quem observa em silêncio aprende o que as palavras não explicam.",
      "Quem oferece descanso também encontra abrigo.",
      "Quem olha os problemas de perto demais deixa de ver as soluções ao redor.",
      "Quem planta compreensão colhe relacionamentos duradouros.",
      "Quem planta coragem colhe novos horizontes.",
      "Quem planta paciência colhe resultados que duram.",
      "Quem protege sua paz encontra sempre um jeito de seguir.",
      "Quem sabe ouvir o próprio coração não se perde em vozes alheias.",
      "Quem semeia respeito anda em solo firme.",
      "Quem sorri para a vida a convida para dançar.",
      "Quem sustenta a própria palavra constrói pontes de confiança.",
      "Quem troca reclamação por ação vê a sorte mudar de lado.",
      "Quem vê só espinhos nas flores esquece que existe perfume.",
      "Saber a hora de recuar também é uma forma de coragem.",
      "Se a crítica for justa, agradeça; se não for, deixe que o vento a leve.",
      "Se a estrada parecer longa, conte passos, não quilômetros.",
      "Se a palavra não ajuda, é melhor que ela descanse na mente.",
      "Se a porta se fechou, talvez não fosse o seu templo.",
      "Se a vida apertar, afrouxe o coração, não a esperança.",
      "Se precisa gritar, que seja de alegria, não de raiva.",
      "Se quiser colher paz, plante compreensão em todas as conversas.",
      "Se quiser ir longe, cuide bem de quem caminha ao seu lado.",
      "Seu coração é um jardim: retire as ervas daninhas dos pensamentos.",
      "Seu amanhã começa nos pensamentos que você escolhe agora.",
      "Sorria com sinceridade: o mundo inteiro entende essa língua.",
      "Sorrir mesmo em dias nublados é convidar o sol a voltar.",
      "Sua atitude é o pincel que colore o quadro da sua vida.",
      "Sua paz vale mais que qualquer discussão vencida.",
      "Um coração calmo enxerga oportunidades onde outros veem problemas.",
      "Um passo honesto vale mais do que uma corrida de aparências.",
      "Um pouco de gentileza muda o clima de qualquer lugar.",
      "Um sorriso corajoso é a primeira vitória sobre a tristeza.",
      "Um único gesto de amor vale mais que mil boas intenções.",
      "Use as pedras do caminho para construir degraus, não muros.",
      "Valorize quem fica ao seu lado nos dias de silêncio.",
      "Vença o dia não com força, mas com serenidade.",
      "Você não controla o vento, mas pode aprender a dançar com ele.",
      "Você não é o que lhe aconteceu; é o que decide fazer com isso hoje.",
      "Você pode não mudar o mundo, mas pode mudar o mundo de alguém hoje.",
      "Você pode ver problemas ou oportunidades; o que cresce é aquilo que você escolhe regar."
    )

  }
}
